services:
  dvna:
    image: ianou27/log8100_tp2:latest
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "9090:9090"
    depends_on:
      - db
    networks:
      - dvnaNet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres:14
    container_name: dvna_db
    expose:
      - "5432"
    networks:
      - dvnaNet
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  dvnaNet:
    driver: bridge

volumes:
  db_data:
