name: Publish Docker image

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      # Step 1: Check out the repo
      - name: Check out the repo
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and tag the Docker image
      - name: Build and tag Docker image
        run: |
          docker compose -f docker-compose.yml build
          docker tag ianou27/log8100_tp2:latest ianou27/log8100_tp2:${{ github.sha }}

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ianou27/log8100_tp2:${{ github.sha }}
          docker push ianou27/log8100_tp2:latest

      # Step 5: Clean up Docker images locally
      - name: Clean up Docker images
        run: |
          docker rmi ianou27/log8100_tp2:${{ github.sha }}
          docker rmi ianou27/log8100_tp2:latest
