name: Security Tests and GitHub Pages Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  security-tests:
    name: Run Snyk Security Tests
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Update package.json
        run: |
          sed -i 's/"bcrypt": ".*"/"bcryptjs": "^2.4.3"/' package.json
          sed -i 's/require("bcrypt")/require("bcryptjs")/' $(grep -rl 'require("bcrypt")' .)
      
      - name: Install project dependencies
        run: npm install
      
      - name: Install Snyk
        run: npm install -g snyk
      
      - name: Run Snyk to check for vulnerabilities
        run: |
          snyk test --json-file-output=snyk.json || true
          snyk test --sarif-file-output=snyk.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: snyk

      - name: Generate HTML report
        run: |
          if [ -f snyk.json ]; then
            npx snyk-to-html -i snyk.json -o snyk-results.html
          else
            echo "JSON file does not exist. Cannot generate HTML report."
          fi
        continue-on-error: true

      - name: Upload Snyk HTML report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-results
          path: snyk-results.html
        if: always()

  deploy-to-github-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write  # Added for enabling Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
