name: Snyk Security Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  security-tests:
    name: Run Snyk Security Tests
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get Node v8
        uses: actions/setup-node@v3
        with:
          node-version: 8.17.0
      
      - name: Install dependencies
        run: npm install
        
      # Step 2: Set up Snyk
      - name: Set up Snyk
        uses: snyk/actions/setup@master
      
      # Step 3: Run Snyk to check for vulnerabilities and generate SARIF
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --json | snyk-to-html -o snyk-results.html
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 4: Generate SARIF file from Snyk results
      - name: Generate SARIF file
        run: |
          npm install -g @snyk/snyk-sarif-parser
          snyk test --json | snyk-sarif-parser > snyk.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 5: Upload SARIF file
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: snyk

      # Step 6: Upload Snyk HTML report as artifact
      - name: Upload Snyk HTML report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-results
          path: snyk-results.html
